import Navbar from "@/components/layouts/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProductPageLayout({ children }) {
  return (
    <main>
      <Navbar />
      {children}
    </main>
  );
}
